set_output:
  name: "Set Output"
  description: "Set the value of an output on the controller e.g. setting the lights to AUTO (Automatic) instead of using the switch entity in HA which only supports OFF/ON."
  fields:
    did:
      name: "Device ID"
      description: "Device ID of selected output, can be obtained from attributes of the given switch in HA."
      example: "3_1"
      selector:
        text:
    setting:
      name: "Setting"
      description: "Target setting for the output, one of: ON/OFF/AUTO"
      selector:
        select:
          options:
            - "OFF"
            - "ON"
            - "AUTO"
set_variable:
  name: "Set Variable"
  description: "Ability to program variables on the controller e.g. Set 75 (Only Advanced mode variables supported currently!!"
  fields:
    did:
      name: "DID"
      description: "DID of the selected variable or output to modify"
      example: "Cntl_A1"
      selector:
        text:
    code:
      name: "Code"
      description: "Code to modify on the variable/output"
      example: "Set 75"
      selector:
        text:
set_dosing_rate:
  name: "Set Dosing Rate"
  description: "Set the dosing rate for a DOS or DQD dosing pump"
  fields:
    did:
      name: "DID"
      description: "DID of the dosing pump"
      example: "4_1"
      selector:
        text:
    profile_id:
      name: "Profile ID"
      description: "Profile ID to assign to the dosing pump, the integration will rename it appropriately."
      example: 11
      selector:
        text:
    rate:
      name: "Rate"
      description: "The desired dosing rate, in mL / min. (effective range is 0 - 125)"
      example: 1.2
      selector:
        text:
refill_reservoir:
  name: "Refill Reservoir"
  description: "Refill the reservoir for a DOS or DQD dosing pump"
  fields:
    did:
      name: "DID"
      description: "DID of the DOS or DQD pump"
      example: "4_1"
      selector:
        text:
set_temperature:
  name: "Set Temperature"
  description: "Set an outlet to be a heater with the given target temperature "
  fields:
    did:
      name: "DID"
      description: "DID of the Heater"
      example: "2_7"
      selector:
        text:
    temperature:
      name: "Temperature"
      description: "The desired temperature (degrees in Apex configured units)"
      example: 80
      selector:
        text:
